version: '3'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python ./awtest/etl.py && python ./run.py"
    ports:
      - "5000:5000"
    volumes:
      - .:/myapp
    depends_on:
      - db

volumes:
  postgres_data: